### ISSUE TITLE
Change the launcher icon

### ISSUE THREAD

**Issue by Kartikdot** [Kartik2016/Currency-Converter#7]
Please discuss in the comments before making a PR.

**Comment by deveshd2k** [comment]
What kind of icon you want? 
I can help with that

**Comment by Kartikdot** [comment]
Hi @deveshd2k , since the app converts currencies i am looking for something that depicts the same. Have a look at the existing icon.
Please share images of the icons that you find fit. Also fork the repo, create a new branch and make a PR fro that branch. Ask here if you need any help.

**Comment by deveshd2k** [comment]
i can add a jpg or psd file of an icon if it is okay.

**Comment by Kartikdot** [comment]
The icon needs to be in the png format and the file should be named icon.png. The file will go into Currency-Converter/app/src/main/res/mipmap folder. There are multiple mipmap folders for different dpi's. Just add the icon to all folders

**Comment by deveshd2k** [comment]
Okay. no problem.

**Comment by maitreyav** [comment]
I know someone else is working on this but I thought I'd do it as well since more choices is better, right? 😄 PR #8

**Comment by Kartikdot** [comment]
Hey @maitreyav , since @deveshd2k was already working on it you should have asked in the comments firts. Nevertheless lets give @deveshd2k one more day to see if any progress is made.

**Comment by deveshd2k** [comment]
@Kartik2016 I have submitted the pr #9 
only difference is that i manually designed it

**Comment by maitreyav** [comment]
@Kartik2016, Yes, I thought you explained already what needed to be done so I didn't commented.

**Comment by Kartikdot** [comment]
Ok @deveshd2k . A small tip, always reference the issue from the PR.

**Comment by maitreyav** [comment]
@Kartik2016, I would like to know your thoughts on #9.

**Comment by maitreyav** [comment]
@Kartik2016, I would like to know your thoughts on #8 .

**Comment by maitreyav** [comment]
@Kartik2016, Just wanted to let you know, this is a bad practice in my opinion that you don't give any response to the contribution made towards your project. It could be good or bad but you should let know contributor what is your opinion to drive the process of design. #8

**Comment by maitreyav** [comment]
@Kartik2016, Just wanted to let you know, this is a bad practice in my opinion that you don't give any response to the contribution made towards your project. It could be good or bad but you should let know the contributor what is your opinion. #8

**Comment by maitreyav** [comment]
@Kartik2016, Just wanted to let you know, this is a bad practice in my opinion that you don't give any response to the contribution made towards the project. It could be good or bad but you should let know the contributor what is your opinion so that it follows the ethos of open source.

**Comment by Kartik2016** [comment]
Yes you are right. But before preaching and writing long paragraphs have a look at what you did. First introspect before throwing on heavy words. You didn't bother to ask if you could work on it before making a PR. Clearly that does not follow the ethos of open source. Just to make it clear to you this is not a COMPETITON. When you had clearly read in the comments that someone was already working on the issue you should have asked to check the progress. So the "bad practice" was started by you. The issue was opened with the hacktoberfest tag to get begginers going with git and github. Since you claim to know so much about good and bad practices, you should follow them first before preaching.
